export const AUTH_SIGN_UP = 'AUTH_SIGN_UP'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT'
export const AUTH_LOG_IN = 'AUTH_LOG_IN'
export const DASHBOARD_GET_DATA = 'DASHBOARD_GET_DATA' 
